FROM python:2-onbuild
RUN python ./db_create.py
RUN python ./db_migrate.py

#ENV APP_DEBUG
#ENV APP_TESTING
#ENV APP_SECRET_KEY
#ENV APP_GOOGLE_API_KEY
#ENV APP_RECAPTCHA_PUBLIC_KEY
#ENV APP_RECAPTCHA_PRIVATE_KEY
#ENV APP_MAIL_SERVER
#ENV APP_MAIL_PORT
#ENV APP_MAIL_USERNAME
#ENV APP_MAIL_PASSWORD

CMD [ "python", "./run.py" ]

# TODO: Switch some config to environment variables